AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-n4uau8}
AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-gi47df}
#AWS_REGION=${AWS_REGION:-eu-west-1}
AWS_REGION=${AWS_REGION:-localhost}

export AWS_ACCESS_KEY_ID
export AWS_SECRET_ACCESS_KEY
export AWS_REGION
