apiVersion: com.ie.ibm.hpsys/v1alpha1
kind: Dataset
metadata:
  name: data-s3
spec:
  local:
    type: "COS"
    secret-name: "cluster-user-creds"
    secret-namespace: "dlf"
    endpoint: "https://s3.eu-west-1.amazonaws.com"
    bucket: "bucket-data-dev"
    readonly: "false"
    region: ""
