include "default-core"
include "default-http"

http {
  routes {
    # need a long timeout for Balance queries (long)
    ask-timeout = 10s
  }
}

datastore="mem://"

chain="""
    ethereum=1=kafka://haas-dev-kafka1.hacken.dev:9092/ethereum.mainnet.tx,
    ethereum_sepolia=11155111=kafka://haas-dev-kafka1.hacken.dev:9092/ethereum.sepolia.tx,

    hyperevm=999=kafka://haas-dev-kafka1.hacken.dev:9092/hyperevm.mainnet.tx,
"""

# chain="""
#     ethereum=1=kafka://haas-dev-kafka1.hacken.dev:9092/ethereum.mainnet.block,    
# """

#output="https://POST@{ACCESS_TOKEN}@api.dev.extractor.live/api/v1/notifications"
output="https://POST@{ACCESS_TOKEN}@notify-proxy.dev.extractor.live/api/v1/notify/broadcast"
format="json"
