include "default-core"
include "default-http"

http {
  routes {
    # need a long timeout for Balance queries (long)
    ask-timeout = 10s
  }
}

#datastore="none://"

chain="""
    ethereum=1=kafka://haas-dev-kafka1.hacken.dev:9092/ethereum.mainnet.tx,
    ethereum_sepolia=11155111=kafka://haas-dev-kafka1.hacken.dev:9092/ethereum.sepolia.tx,
"""
