version: '3'
services:
  mysql-1:
    image: mysql/mysql-server:8.0
    volumes:
      - "./db:/var/lib/mysql-db"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      MYSQL_HOST: 0.0.0.0
      MYSQL_DATABASE: otp_db
      MYSQL_USER: otp_user
      MYSQL_PASSWORD: otp_user
