version: '3'
services:
  # mysql-1:
  #   image: mysql/mysql-server:8.0
  #   volumes:
  #     - "./db:/var/lib/mysql-db"
  #   restart: always
  #   ports:
  #     - 3306:3306
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_ROOT_HOST: '%'
  #     MYSQL_HOST: 0.0.0.0
  #     MYSQL_DATABASE: world_db
  #     MYSQL_USER: world_user
  #     MYSQL_PASSWORD: world_pass

  shop-1:
    image: syspulse/skel-shop:0.0.1
    volumes:
      - "${CONFIG_DIR}:/app/conf"
    restart: always
    ports:
      - 8083:8080
    environment:
      SITE: $SITE
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      #AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN:-}
      
