---
apiVersion: v1
kind: Pod
metadata:
  name: iscsipd
spec:
  containers:
  - name: iscsipd-rw
    image: kubernetes/pause
    volumeMounts:
    - mountPath: "/mnt/iscsipd"
      name: iscsipd-rw
  volumes:
  - name: iscsipd-rw
    iscsi:
      targetPortal: 192.168.1.18:3260
      portals: ['192.168.1.18']
      iqn: iqn.2000-01.com.synology:nas-1.Target-1.ce1c31bdfb
      lun: 0
      fsType: ext4
      readOnly: true


