---
apiVersion: v1
kind: Pod
metadata:
  name: iscsipd
spec:
  containers:
  - name: alpine
    image: alpine:latest
    command: ["/bin/sh", "-c"]
    args:
      - while true; do echo `date`; ls -l /mnt/iscsipd; sleep 1; done;
    volumeMounts:
    - mountPath: "/mnt/iscsipd"
      name: iscsipd-rw
  volumes:
  - name: iscsipd-rw
    iscsi:
      chapAuthDiscovery: false
      chapAuthSession: false
      targetPortal: 192.168.1.18
      iqn: iqn.2000-01.com.synology:nas-1.Target-1.ce1c31bdfb
      lun: 1
      fsType: ext4
      readOnly: true
