include "default-core"
include "default-http"

http {
  routes {
    ask-timeout = 60s
  }
}
akka.http.server.request-timeout = 90s

timeout = 30000

postgres {
  dataSourceClassName=org.postgresql.ds.PGSimpleDataSource
  dataSource.url=${?DB_URL}
  dataSource.user=${?DB_USER}
  dataSource.password=${?DB_PASS}
  connectionTimeout=30000
  idleTimeout=30000
  minimumIdle=5
  maximumPoolSize=20
  poolName=DB-Pool
  maxLifetime=2000000
}

postgres2 {
  dataSourceClassName=org.postgresql.ds.PGSimpleDataSource
  dataSource.url="jdbc:postgresql://localhost:5432/explain_db"  
  dataSource.user=explain_user
  dataSource.password=explain_pass
  connectionTimeout=30000
  idleTimeout=30000
  minimumIdle=5
  maximumPoolSize=20
  poolName=DB-Pool
  maxLifetime=2000000
}


datastore = "mem://"

permissions = "user"

jwt {
  uri = "hs512://"
}
