include "default-core"
include "default-http"

http {
  routes {
    ask-timeout = 60s
  }
}
akka.http.server.request-timeout = 90s

timeout = 30000

# Async postgres
postgres {
  dataSourceClassName=org.postgresql.ds.PGSimpleDataSource
  url="jdbc:postgresql://localhost:5432"
  #url="jdbc:postgresql://222222222222222222222222222222222222222222222222222222222222:5432"
  #dataSource.url="jdbc:postgresql://444444444444444444444444444:5432"
  #url=${DB_URL}
  #host=localhost  
  database=explain_db
  username=explain_user
  password=explain_pass
  dataSource.connectionProperties="TimeZone=UTC;binaryTransfer=false;disableTimeZone=true"
  numThreads = 10  
}

# Sync postgres
postgres1 {
  dataSourceClassName=org.postgresql.ds.PGSimpleDataSource
  dataSource.url="jdbc:postgresql://localhost:5432/explain_db"  
  dataSource.user=explain_user
  dataSource.password=explain_pass
  dataSource.connectionProperties="TimeZone=UTC;binaryTransfer=false;disableTimeZone=true"
  connectionTimeout=30000
  idleTimeout=30000
  minimumIdle=5
  maximumPoolSize=20
  poolName=DB-Pool
  maxLifetime=2000000
}

postgres_db {
  dataSourceClassName=org.postgresql.ds.PGSimpleDataSource
  url=${DB_URL}
  #host=localhost  
  database=${DB_DATABASE}
  username=${DB_USER}
  password=${DB_PASS}
  dataSource.connectionProperties="TimeZone=UTC;binaryTransfer=false;disableTimeZone=true"
  numThreads = 10  
}

#datastore = "mem://"
datastore = "jdbc://postgres"

permissions = "user"

jwt {
  uri = "hs512://"
}
