include "default-core"
include "default-http"

http {
  routes {
    ask-timeout = 60s
  }
}

akka.http.server.request-timeout = 90s

timeout = 30000

datastore = "mem://"

permissions = "user"

jwt {
  uri = "hs512://"
}
