apiVersion: v1
kind: Pod
metadata:
  name: alpine
spec:
  containers:
  - name: alpine
    image: alpine:latest
    ports:
    - containerPort: 9876
    command: ["/bin/sh", "-c"]
    args:
      - while true; do echo `date`; ping 192.168.1.18; sleep 1; done;

