version: "3"

networks:
  twit:

#volumes:
#  app_data: 
#  graphite_data:

services:
  # prometheus:
  #   image: prom/prometheus:v2.21.0
  #   restart: always
  #   container_name: prometheus
  #   volumes:
  #     - ./prometheus/:/etc/prometheus/
  #   command:
  #     - "--config.file=/etc/prometheus/prometheus.yml"
  #     - "--storage.tsdb.path=/prometheus"
  #   ports:
  #     - 9090:9090
  #   networks:
  #     - twit
  
  cassandra:
    image: cassandra:4.0.1
    restart: always
    container_name: cassandra
    ports:
      - "9042:9042"
    volumes:
    # ATTENTION: conainer cannot start on fcrypt-ed volume!!!
      - ../../infra/cassandra/data:/var/lib/cassandra
    environment:
      - NONE:1
    networks:
      - twit
