include "default-core"
include "default-http"

http {
  routes {
    # LLM questions can take a long time to answer
    ask-timeout = 100s
  }
}

# Timeout for HTTP should be bigger than ask-timeout
akka.http.server.request-timeout = 120s

# timeout for Agent/LLM questions
timeout = 60000

postgres {
  dataSourceClassName=org.postgresql.ds.PGSimpleDataSource
  dataSource.url=${?DB_URL}
  dataSource.user=${?DB_USER}
  dataSource.password=${?DB_PASS}
  dataSource.connectionProperties="TimeZone=UTC;binaryTransfer=false;disableTimeZone=true"
  connectionTimeout=30000
  idleTimeout=30000
  minimumIdle=5
  maximumPoolSize=20
  poolName=DB-Pool
  maxLifetime=2000000
}

# datastore = "jdbc://postgres"
datastore = "dir:///mnt/s3/data/dev/dashboard"

ds = """many://
  test://,
  ess://{ES_USER}:{ES_PASS}@{ES_HOST}?compress=true,
  dune://{DUNE_API_KEY},
  coingecko://{CG_API_KEY},
  postgres://{DB_USER}:{DB_PASS}@{DB_HOST}/{DB_NAME}?TimeZone=UTC
"""


