include "default-core"
include "default-http"

http {
  routes {
    # LLM questions can take a long time to answer
    ask-timeout = 100s
  }
}

# Timeout for HTTP should be bigger than ask-timeout
akka.http.server.request-timeout = 120s

# timeout for Agent/LLM questions
timeout = 60000

postgres {
  dataSourceClassName=org.postgresql.ds.PGSimpleDataSource
  dataSource.url=${?DB_URL}
  dataSource.user=${?DB_USER}
  dataSource.password=${?DB_PASS}
  dataSource.connectionProperties="TimeZone=UTC;binaryTransfer=false;disableTimeZone=true"
  connectionTimeout=35000
  idleTimeout=35000
  minimumIdle=5
  maximumPoolSize=24
  poolName=DB-Pool
  maxLifetime=2000000
}

datastore = "jdbc://postgres"
#datastore = "dir:///mnt/s3/data/prod/dashboard"

ds = """many://
  test://,
  dune://{DUNE_API_KEY},
  coingecko://{CG_API_KEY},  
"""

