version: '3'

networks:
  mysql:

services:
  mysql-1:
    image: mysql/mysql-server:8.0
    container_name: mysql
    volumes:
      - "${PWD}/db_data:/var/lib/mysql-db"
    restart: always
    ports:
      - 3306:3306
    networks:
      - mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      MYSQL_HOST: 0.0.0.0
      MYSQL_DATABASE: medar_db
      MYSQL_USER: medar_user
      MYSQL_PASSWORD: medar_pass
